### PR TITLE
Bugfix - Create a custom tooltip popover.

### PR DESCRIPTION
**Pull request by hotoiledgoblinsack**
Hello

Seeing as it turns out I've been abusing Atom's tooltips and there is no actual popover implementation available in Atom (yet), I've replaced them with a custom simple popover.

I really didn't want to have to create a custom implementation for this, but it seems, for the moment, we have little choice (that is at least if we want to see these issues resolved). Note the following things:
  * The popover does not try to intelligently place itself somewhere in the editor. It just puts the arrow in the center of the word and is displayed about 12.5% of the width of the tooltip. Very very wide popovers may very well fall off the screen. Popovers will also not position themselves above the word if there is no space at the bottom (but I believe that currently doesn't happen either with our use of Atom's tooltips).
  * I used colors from the Styleguide to style the popover. It looks fine with my color scheme, but it may not in yours or someone else's color scheme. Advice on what colors to use instead is appreciated. I can use colors that look like the original tooltip Atom uses instead, but in my color scheme they are a pretty blinding white on blue, which doesn't really work for large amounts of text such as we have.

On a more positive note, the issues #107 en #72 seem to be resolved with this implementation. This also seems to fix an issue where sometimes tooltips would show up when hovering over entirely different code. The content of popovers are now styled through the stylesheet with classes, instead of manually injecting styling in the code.

Feedback is appreciated.

### CODE REVIEW

**Comment by Peekmo** [comment]
With UI theme "Atom Material" and Syntax "One Light", the tooltip content is unreadable ^^ (light theme)

**Comment by hotoiledgoblinsack** [comment]
I managed to use Atom's tooltip's CSS classes for the custom tooltip. The transitions (animations) and styling should now be exactly the same as previously (with the exception of the positioning, as is described above). Is it better for you now?

**Comment by Peekmo** [comment]
Amazing ! Thank you !

**Comment by Peekmo** [comment]
Just to say @hotoiledgoblinsack , it works really really perfectly. Congratulations !

**Comment by hotoiledgoblinsack** [comment]
Thanks, but the credit mostly goes to you for providing a good package base to start!

**Pull request merged**
