### PR TITLE
Enhancement - Ticket #121 - Implement tooltips for classes.

### PR DESCRIPTION
**Pull request by hotoiledgoblinsack**
Hello

This implements ticket #121. Classes, interfaces and traits will now have tooltips showing their documentation. The tooltip shows the class name, the full class name, the summary and the long description (if it is available).

As a nice side effect, use statements that point to a class, trait or interface will also have tooltips.

### CODE REVIEW

**Comment by Peekmo** [comment]
Nice :+1:

**Comment by Peekmo** [comment]
The class tooltips doesn't hide when you scroll (same as old #107)

**Comment by hotoiledgoblinsack** [comment]
I've noticed the same thing, I think I know what's causing it and will try to look at solving it soon.

**Comment by hotoiledgoblinsack** [comment]
Fixed in pull request #176.

**Pull request merged**
