### PR TITLE
Go to class / method support and small fix

### PR DESCRIPTION
**Pull request by CWDN**
## Go to functionality
You are now able to `alt-click` on classes and methods. Even classes within comments!

Also you are able to backtrack through you clicks with `Ctrl + Shift + Z`

This GIF should explain everything.

desktop-animation

### Limitations
* The `alt-click` within comments will only work when the editor is first loaded. If you add any new comments, these won't get the `alt-click` functionality until the editor is reopened. 
* It seems that if the method is within a trait it is unable to pick it up. Need to add some extra checking to look into trait if class is not found in current class or parent.

## Fixes
* Fixed when class namespace is on the same line as `<?php` the autocomplete wouldn't work. 

_Just to note I'm not a JS / Coffeescript developer so if anything is done stupidly or wrong then that will be why._ :dancer:

### CODE REVIEW

**Comment by Peekmo** [comment]
Hello,

Thank you for this amazing feature. I have to take time to test it and validate.
I have a question, why, in some files, are you doing ```self = @``` ?

Regards,
Peekmo

**Comment by CWDN** [comment]
Hi,
Glad you like it. I've only tested this on Fedora 22 using a couple of Laravel projects.

I'm doing `self = @` because from what I understand `@` is an alias for `this`. Now when you call `this` within a closure you are no longer referencing the object that the closure is created in.

For example:
```
class AbstractGoto
...
self = @
atom.workspace.observeTextEditors (editor) ->
    console.log @
    console.log self
```
This will output:
```
Window {top: Window, window: Window, location: Location, document: document, global: Window…}
GotoClass {subAtom: SubAtom, $: function, parser: Object, fuzzaldrin: Object, manager: GotoManager…}
```

I did find that when testing this SubAtom events didn't need the `self = @`.

**Comment by Peekmo** [comment]
Oh ok,

In coffee script, you can use ```=>``` instead of ```->``` to have the context of your class

e.g : 

```coffeescript
class AbstractGoto
...
self = @
atom.workspace.observeTextEditors (editor) =>
    console.log @
    console.log self # should be the same as @
```

**Comment by CWDN** [comment]
Ah ok, updated to remove all the self variables.

**Comment by Peekmo** [comment]
Thank you :)

I tried, and I took a look into your code. Really nice !

Just 2 things before merging : 
- Could you please, add the missing comments above methods ?
- ctrl - alt - click is working nicely, but "f1" is working only on class name, not on methods. Is it working for you ?

Regards,
Peekmo

**Comment by CWDN** [comment]
No problem.

Done the two amendments that you wanted.

**Comment by Peekmo** [comment]
Thank you :+1: 

I think that the next step will be to be able to make it work on multiple level of methods e.g : 
```$this->getDoctrine()->getManagers() // be able to click on getManagers```

But that's already an awesome work, thank you !

**Comment by Peekmo** [comment]
I change the default keymap for goto, ```ctrl - alt - g``` instead of ```f1``` because goto in atom is ```ctrl - g``` and namespace command is ```ctrl - alt - n``` so I prefer to keep it easy to remember. 

If anyone want to use f1, he will have to override configuration.

**Pull request merged**
