### PR TITLE
Bugfix - Consolidate providers and make autocompletion context sensitive.

### PR DESCRIPTION
**Pull request by hotoiledgoblinsack**
Hello

This is a larger pull request that does the following things:
  * The static, self, parent and autocomplete providers have all been merged into one member provider, which provides (what's in a name) the members of an object or class (or keyword). This has reduced a great deal of code duplication.
  * The new member provider is context sensitive, which means that it will only list private members if you're working in the class itself and only protected members when you're working in the class itself or one of its parent classes. This also means that you will no longer see protected and private members that you can't use anyway.
  * Constants are now properly shown again (they seemed to have disappeared).
  * The `parent` keyword works again.
  * You will no longer incorrectly see autocompletion for members of `$this` when typing `$this` (instead of `$this->`).
  * As a side effect, valid PHP code `$this::MY_CONSTANT` now works.
  * Solves #127 and #142.

That's mostly it. The introduced changes will make our autocompletion a great deal more correct and useful. However, as the changes are large, this will require proper testing as usual.

### CODE REVIEW

**Comment by Peekmo** [comment]
Hi thank you.

I'll test it today

**Comment by hotoiledgoblinsack** [comment]
Ok, I'll also be testing it today, and looks like I already found a bug. The regex in member-provider should be:
```
@regex = /(?:[a-zA-Z0-9_]+)(?:\(.*\))?(?:->|::)([a-zA-Z0-9_]*)/g
```

As now it is only autocompleting after the arrow or double colons (it doesn't fuzzy match after that). I'll fix it as soon as I get to my development machine again, but I'm placing it here so you can change it in your local version for testing in the meantime.

**Comment by Peekmo** [comment]
Ok thank you, I'm changing it and push it

**Comment by hotoiledgoblinsack** [comment]
Looks like there's more I broke, this fixes fuzzy matching, but chaining methods now no longer works. This should fix it:

```
@regex = /(?:(?:[a-zA-Z0-9_]+)(?:\(.*\))?(?:->|::))+([a-zA-Z0-9_]*)/g
```

When I was testing this locally I was testing all the different keywords immediately after the -> and ::, which is why I didn't pick up any of these things. But hey, that's what testing is for, right ;-).

**Comment by Peekmo** [comment]
I didn't start to write a PHP code for the moment, so didn't test for the moment ^^

I push your new regex ^^

**Comment by hotoiledgoblinsack** [comment]
Thanks for quickly updating it, I haven't encountered any other bugs after this was fixed.

**Comment by Peekmo** [comment]
Me too, I pushed a new release ;)
Would you like to give me your full name in order to create a CONTRIBUTORS.md in the repo with your full name in (if you want)?

**Comment by hotoiledgoblinsack** [comment]
Sure, I've sent you an email about it (sadly no PM's are possible on GitHub).

**Pull request merged**
