### PR TITLE
Feature - Add a new constant-provider that provides internal PHP constants.

### PR DESCRIPTION
**Pull request by hotoiledgoblinsack**
Hello

This implements #149 and adds a new provider for internal PHP constants.

### CODE REVIEW

**Comment by Peekmo** [comment]
Your too fast, I was finishing it when I saw your PR xD

**Comment by hotoiledgoblinsack** [comment]
Haha, perhaps you can mark a ticket as in progress or assign it to you?

**Comment by Peekmo** [comment]
I will^^

I give you access to the repository too, you'll be able to assign tickets to you too (I guess, could you please confirm). 
But please, continue to use PR in order to be able to follow what is done in the code ;)

**Comment by hotoiledgoblinsack** [comment]
Thanks! I'll keep using pull requests so you can keep reviewing the code (it is your code base after all).

**Pull request merged**
