### PR TITLE
Refactoring/Bugfix - Rename autocompletion provider directory and fix minor issues.

### PR DESCRIPTION
**Pull request by hotoiledgoblinsack**
Hello

This pull request does the following:
  * Autocompletion providers are now in the `autocompletion` directory instead of the `providers` directory, consistent with the other provider directories.
  * Autocompletion providers now go through a manager, also consistent with the other provider directories.
  * Fixed a minor issue in `getVariableType` where it didn't check if a regular expression match was undefined, which could cause problems when checking closures for types.
  * Remove the previous popover when a new popover is shown. This is more of a safety measure as no two popovers can (or should) ever be displayed at the same time anyway.
  * I reactivated the configuration testing by default. I noticed that your fix for Windows broke it for me on Linux, so now both ways (the fix for Windows and the old way) are tested before throwing an error, which allows us to safely enable it again ;-).
  * The automatic adding of use statements and renaming of the completed full class name to just the class name is now grouped inside a transaction. This way you don't have to undo twice (but just once) to get the full class name if you don't want the use statement automatically added. Or, in other words, if you're undoing the rename and using the full class name, you also don't need the use statement anymore. This increases usability a bit.

### CODE REVIEW

**Comment by Peekmo** [comment]
Hello,

Sorry, I thank that I had answered your message in the ticket #93 
I don't want to disable the plugin if the config is bad, because we can't reactive it when the user changed his configuration.

**Comment by hotoiledgoblinsack** [comment]
Ah I see, I've seen Atom popups or notifications that have buttons. Would it perhaps somehow be possible to show a permanent popup that the user can dismiss or click a `Try Again` button on?

**Comment by hotoiledgoblinsack** [comment]
Ok, I've disabled the configuration testing and resolved the conflicts.

**Comment by Peekmo** [comment]
Thanks !

**Pull request merged**
