### PR TITLE
Add tooltips with descriptions on mouse hover.

### PR DESCRIPTION
**Pull request by hotoiledgoblinsack**
Hello

I decided to start tinkering a bit with the code myself, annoying you with pull requests as well as bug reports ;-). This adds support for mouse tooltips when hovering over known methods and properties.

Note the following things:
  * The current timeout for the tooltip is 500ms, which seems reasonable to avoid annoying the user.
  * Tooltips on class names are not implemented as I'm not sure docblocks from classes are even extracted on the PHP side at the moment. I've added a TODO in class-goto for this.
  * Very strangely, I've noticed that sometimes it takes a few mousemove and mouseout events for the tooltip to start showing for the first time, even though the code is actually properly executed. After the initial show, it works as intended for that specific `HTMLElement`.

@CWDN  I've also noticed `mousemove` being used in `abstract-goto.coffee`, causing the method to be invoked on every mouse move, is there a reason `mouseover` isn't used instead?

I have very little experience with CoffeeScript, so feedback is also appreciated in that regard.

Thanks in advance

### CODE REVIEW

**Comment by Peekmo** [comment]
Hello !

Sorry, I'm on hollidays, so I'm not really active this weeks.

I reviewed your PR, and that's pretty nice ! In my opinion, there's something that could be better visually, but I don't know what exactly ^^ So, I merge it even with the problem that you report. It's minor and could be fix later. (I add an issue for that)

Nice work :+1: 
Regards, Peekmo

**Comment by Peekmo** [comment]
Hello,

Don't you think that the "return" and "params" of the method could be write on new line ? Like description or throws for example:

-------------------------------------
myMethod($x, $y)
.....
Description:
      - my super description

Parameters:
     - $x - string - parameter x
     - $y - int      - parameter y

Returns:
     - boolean - Blabla

Throws:
      - ....

-------------------------------

**Comment by hotoiledgoblinsack** [comment]
I agree, but I would also leave the original way intact (I would do both at the same time), as it immediately allows you to see the complete signature of the function or method at a glance. We are currently indeed missing the description of the parameters and the return type. Maybe something like this?

```
bool myMethod(FirstClass $x, SecondClass $y)

This is my method (summary).

Description:
  This is a long description of my method (description).

Parameters:
  $x - FirstClass - Description of parameter x from docblock (if present).
  $y - SecondClass - Description of parameter y from docblock (if present).

Returns:
  bool - Description of return value from docblock (if present).

Throws:
  ...
```

(Which is exactly the same as your example, except for the first line.)

**Comment by Peekmo** [comment]
Yep,  I agree, that will be better :)

**Pull request merged**
