### PR TITLE
Uncaught TypeError: Cannot read property 'length' of undefined Fix #61

### LINKED ISSUE #61: Uncaught TypeError: Cannot read property 'length' of undefined
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.7.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\putude\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:197

TypeError: Cannot read property 'length' of undefined
  at Object.module.exports.isInFunction (C:\Users\putude\.atom\packages\atom-autocomplete-php\lib\services\php-file-parser.coffee:197:65)
  at VariableProvider.module.exports.AbstractProvider.getSuggestions (C:\Users\putude\.atom\packages\atom-autocomplete-php\lib\providers\abstract-provider.coffee:21:52)
  at C:\Users\putude\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:267:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\putude\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:246:17)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\putude\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\putude\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:233:19)
  at C:\Users\putude\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61

```

### Commands

```
     -0:22.5.0 tree-view:collapse-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:17.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:17.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:16.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:16.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:16.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:16.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:15.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:14.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.3.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:12.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:12.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:12.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "atom-autocomplete-php": {
    "binComposer": "composer"
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-autocomplete-php, v0.7.1
atom-html-preview, v0.1.11
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-sass, v0.1.0
change-case, v0.6.0
color-picker, v2.0.11
emmet, v2.3.12
file-icons, v1.6.7
jquery-snippets, v11.0.0
linter, v1.4.3
linter-csslint, v1.0.5
linter-less, v2.1.0
linter-php, v1.0.3
pigments, v0.11.0
Remote-FTP, v0.7.2
text-manipulation, v0.6.0

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by earncef**
The issue with using alt + click on class names still occurred due to classesResponse not being unless and yet not having the autocomplete property. This fixes it.

### CODE REVIEW

**Comment by Peekmo** [comment]
Thank you :)

**Comment by earncef** [comment]
Awesome :)

**Comment by turigeza** [comment]
For me this is  still happening or at least the error reporter says it is this issue:
screen shot 2016-07-12 at 19 56 34


TypeError: Cannot read property 'length' of undefined
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/Users/geza/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:44:33)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/Users/geza/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at HTMLSpanElement.<anonymous> (/Users/geza/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

**Comment by jpmurray** [comment]
[Enter steps to reproduce below:]

1. Use atom
2. See bug appear.

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.19.0


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/jpmurray/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:44

TypeError: Cannot read property 'length' of undefined
    at FunctionProvider.module.exports.FunctionProvider.getTooltipForWord (/Users/jpmurray/.atom/packages/atom-autocomplete-php/lib/tooltip/function-provider.coffee:44:33)
    at FunctionProvider.module.exports.AbstractProvider.showPopoverFor (/Users/jpmurray/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:109:24)
    at HTMLSpanElement.<anonymous> (/Users/jpmurray/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:78:22)
    at HTMLDivElement.jQuery.event.dispatch (/Users/jpmurray/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Users/jpmurray/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:02.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:02.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:01.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:01.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:01.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:01.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:00.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:00.8.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:00.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:00.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:00.8.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:00.6.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:00.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:00.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:00.6.0 editor:indent (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.19.0 (active)
atom-beautify, v0.29.11 (active)
atom-ctags, v5.0.0 (active)
auto-update-packages, v1.0.1 (active)
blade-snippets, v0.2.0 (inactive)
docblockr, v0.8.5 (active)
file-icons, v1.7.19 (active)
highlight-selected, v0.11.2 (active)
hyperclick, v0.0.37 (active)
hyperclick-php, v0.2.1 (active)
language-blade, v0.25.3 (active)
less-than-slash, v0.16.0 (active)
linter, v1.11.16 (active)
linter-jshint, v2.1.0 (active)
linter-php, v1.2.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-codeglance, v0.4.5 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.1.1 (active)
minimap-selection, v4.4.0 (active)
open-in-browser, v0.4.7 (inactive)
php-cs-fixer, v2.5.9 (active)
pigments, v0.34.0 (active)
project-manager, v2.9.7 (active)
sync-settings, v0.7.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Pull request merged**
